pipeline {
  agent {
    node {
      label 'any' 
    }
  }    
   stages {
        stage('Build') {
            steps {
                sh './create-catalog.sh mycatalog'
            }
        }
    }
}
