pipeline {
  agent {
    node {
      label 'nodejs' 
    }
  }   

    parameters {
        string(name: 'CATALOG_NAME',  description: 'the name of the catalog. the created tar.gz will be named $CATALOG_NAME.tar.gz')
        string(name: 'POST_CATALOG_CREATION_SCRIPT', description: 'command to run after the tar.gz file is created (use this to curl/upload file somewhere, like a repository')
    }
 
   stages {
        stage('Build') {
            steps {
                sh "cd operatorhub-catalog; ./create-catalog.sh ${params.CATALOG_NAME}"
            }
        }
        stage('Post-build'){
            steps {
                sh "${params.POST_CATALOG_CREATION_SCRIPT}"
            }
        }
    }
}
